### ISSUE TITLE
[TASK] Remove initial filter for cantonal executive

### ISSUE THREAD

**Issue by lorenzulrich** [visol/ext-easyvote_smartvote#10]
Cantonal executive are only a bunch of candidates. Therefore there should be no initial filter but just the unfiltered list of candidates. The filter plugin should of course still apply if someone wants to use it.

**Comment by fabarea** [comment]
Can you confirm it is what it is meant?

<img width="523" alt="2016-02-10_1159" src="https://cloud.githubusercontent.com/assets/620730/12945486/f59e919e-cfed-11e5-81e2-fdc92e2cea61.png">

**Comment by lorenzulrich** [comment]
The goal is that the list of candidates for cantonal executive is immediately available. So the ideal thing would be:
- Remove filter as suggested
- Display link to Fragebogen / Anmelden if necessary on top of the candidates.

Possible?

**Comment by fabarea** [comment]
If no question has been filled, display section "zum Fragebogen" or "anmelde". Otherwise, display list of candidates for executive election scope.

Update: do not roll out the code yet. The compile JS has not be committed yet.
